---
#
# Revised to follow the docker compose v2 file specification
# (not to be confused with compose v1 and Version 1, Version2,
# or Version 3 file formats).

# Original notes below
# Derived from example provided by Tony Lawrence - see
# http://tonylawrence.com/posts/unix/synology/free-your-synology-ports/
#
# Extended to include multiple services using a separate macvlan
# Macvlan provides unique IP addresses for each container.
#
# ipam configuration options used in the macvlan below
# e.g. aux_addresses are not available in docker-compose
# version 3.x at this time so this compose file needs to use
# the 2.x format.

# uncomment to set project name in docker; otherwise default
# name derived from directory name is used
# name: lan_services

# include attribute available in compose 2.20 and newer
include:
# registry service replaced for forgejo
#  - ./services/registry.yaml
  - ./services/pihole.yaml
#  - ./services/pihole-test.yaml
  - ./services/homeassistant.yaml
  - ./services/forgejo.yaml
  - ./services/caddy.yaml
  - ./services/unifi.yaml
#  10 Feb 2025 - doh client replaced by pfsense and DOT
#  - ./services/doh-client.yaml
  - ./services/smokeping.yaml

networks:
  macvlan1:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.110.0/24
          gateway: 192.168.110.1
          ip_range: 192.168.110.192/26
          aux_addresses:
            -host: 192.168.110.193
  unifibridge1:
    driver: bridge

secrets:
  pihole_webpasswd:
    file: pihole_password.txt
  pihole_primary:
    file: pihole_primary.txt
  pihole_replicas:
    file: pihole_replicas.txt
...
