#
# FarmOS docker-compose
#
# Use with -f parameter; e.g.
# docker-compose -f docker-compose.yaml - f docker-compose-farmos.yaml pull
#

# ipam configuration options used in the macvlan below
# e.g. aux_addresses are not available in docker-compose
# version 3.x at this time so this compose file needs to use
# the 2.x format.

version: '2.4'

services:
  mariadb:
    container_name: SageCreek-MariaDB
    image: mariadb:latestmariadb
    hostname: mariadb
    domainname: lan             # <-- Update
    mac_address: d0:ca:ab:cd:ef:06
    networks:
      macvlan1:
        ipv4_address: 192.168.110.206   # <-- Update
    volumes:
      - /volume1/docker/farmos/db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3306/tcp
    environment:
      MYSQL_ROOT_PASSWORD: farm
      MYSQL_DATABASE: farm
      MYSQL_USER: farm
      MYSQL_PASSWORD: farm
    restart: unless-stopped
  farmos:     # Farm OS Drupal
    container_name: SageCreek-FarmOS
    image: farmos/farmos:7.x-1.4
    hostname: farmos
    domainname: lan
    mac_address: d0:ca:ab:cd:ef:07
    networks:
      macvlan1:
        ipv4_address: 192.168.110.207
    volumes:
      - /volume1/docker/farmos/sites:/var/www/html/sites
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80/tcp
      - 443/tcp
    restart: unless-stopped
