---
# caddy service
services:
  caddy:
    image: caddy:latest
    container_name: Caddy
    restart: unless-stopped
    networks:
      macvlan1:
        ipv4_address: 192.168.110.214
    cap_add:
      - NET_ADMIN
    ports:
      - '80'
      - '443'
      - '443/udp'
    volumes:
      - /volume1/docker/caddy/etc:/etc/caddy
      - /volume1/docker/caddy/site:/srv
      - /volume1/docker/caddy/data:/data
      - /volume1/docker/caddy/config:/config

...
