---
# pihole dns services
#
services:
  # nebula sync to keep multiple instances in sync
  # Use IP addresses for pihole instances due to dns configuration
  # on host synology - To Be Fixed
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    user: 1000:1000
    networks:
      macvlan1:
        ipv4_address: 192.168.110.206
    secrets:
      - pihole_primary
      - pihole_replicas
    environment:
    # PRIMARY and REPLICAS not used with docker compose secrets
    #  PRIMARY: https://192.168.110.202
    #  REPLICAS: https://192.168.110.201
      PRIMARY_FILE: /run/secrets/pihole_primary
      REPLICAS_FILE: /run/secrets/pihole_replicas

      TZ: 'America/Los_Angeles'
      CLIENT_SKIP_TLS_VERIFICATION: true
      FULL_SYNC: false
      RUN_GRAVITY: false

      SYNC_CONFIG_DNS: true
      SYNC_CONFIG_DHCP: false
      SYNC_CONFIG_NTP: true
      SYNC_CONFIG_RESOLVER: true
      SYNC_CONFIG_DATABASE: true
      SYNC_CONFIG_MISC: false
      SYNC_CONFIG_DEBUG: false

      SYNC_GRAVITY_DHCP_LEASES: false
      SYNC_GRAVITY_GROUP: true
      SYNC_GRAVITY_AD_LIST: true
      SYNC_GRAVITY_AD_LIST_BY_GROUP: true
      SYNC_GRAVITY_DOMAIN_LIST: true
      SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP: true
      SYNC_GRAVITY_CLIENT: false
      SYNC_GRAVITY_CLIENT_BY_GROUP: false

      CRON: '*/15 * * * *'
    restart: unless-stopped

  # v6 pihole - primary for nebula-sync
  # dns_secret defined in compose.yaml
  piholev6:     # Pi Hole dns server for local network
    container_name: Pi-Hole-V6
    image: pihole/pihole:latest
    hostname: pihole2
    domainname: lan
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
      - NET_BIND_SERVICE
    networks:
      macvlan1:
        ipv4_address: 192.168.110.202
    volumes:
      - '/volume1/docker/piholev6/pihole-configs:/etc/pihole/'
      - '/volume1/docker/piholev6/dnsmasq.d-configs:/etc/dnsmasq.d/'
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 80/tcp
    environment:
      WEBPASSWORD_FILE: pihole_webpasswd
      TZ: 'America/Los_Angeles'
    secrets:
      - pihole_webpasswd
    restart: unless-stopped

  # v6 pihole - replica for nebula-sync
  # Uses original pihole v5 IP and domain name
  # dns_secret defined in compose.yaml
  pihole:     # Pi Hole dns server for local network
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    domainname: lan
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
      - NET_BIND_SERVICE
    networks:
      macvlan1:
        ipv4_address: 192.168.110.201
    volumes:
      - '/volume1/docker/pihole/etc:/etc/pihole/'
      - '/volume1/docker/pihole/dnsmasq:/etc/dnsmasq.d/'
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 80/tcp
    environment:
      WEBPASSWORD_FILE: pihole_webpasswd
      TZ: 'America/Los_Angeles'
    secrets:
      - pihole_webpasswd
    restart: unless-stopped

...
