---
# pihole dns services
#
services:
  # v6 pihole
  # dns_secret defined in compose.yaml
  piholev6:     # Pi Hole dns server for local network
    container_name: Pi-Hole-V6
    image: pihole/pihole:latest
    hostname: pihole2
    domainname: lan
  #  depends_on:   - doh-client no longer used
  #    - doh-client
    cap_add:
      - NET_ADMIN
    networks:
      macvlan1:
        ipv4_address: 192.168.110.202
    volumes:
      - '/volume1/docker/piholev6/pihole-configs:/etc/pihole/'
      - '/volume1/docker/piholev6/dnsmasq.d-configs:/etc/dnsmasq.d/'
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    environment:
      FTLCONF_webserver_api_password: pihole_webpasswd
      TZ: 'America/Los_Angeles'
    secrets:
      - pihole_webpasswd
    restart: unless-stopped
