---
# docker registry service
#
services:
  registry:      # Docker registry server for local development
    container_name: Registry
    restart: always
    image: registry:2
    hostname: reg
    domainname: lan
    mac_address: d0:ca:ab:cd:ef:10
    networks:
      macvlan1:
        ipv4_address: 192.168.110.210
    ports:
      - 443/tcp
      - 443/udp
    volumes:
      - /volume1/docker/registry:/var/lib/registry
      - /volume1/docker/registry/certs:/certs
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:443
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
...
