---
# unifi network application services
# includes mondodb and logs services

services:
  unifi:
    image: "buckaroogeek/unifi:v9"
    container_name: Unifi-Network-Application
    hostname: unifi2
    domainname: lan
    depends_on:
      - mongo
    init: true
    networks:
      macvlan1:
        ipv4_address: 192.168.110.216
      unifibridge1:
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/unifi2:/unifi
      - /volume1/docker/unifi2/run:/var/run/unifi
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
      TZ: America/Los_Angeles
      UNIFI_HTTP_PORT: 80
      UNIFI_HTTPS_PORT: 443
    ports:
      - "1900/udp"    # L2 discovery
      - "3478/udp"    # STUN
      - "6789/tcp"    # Speed test
      - "80/tcp"      # Device/ controller comm.
      - "443/tcp"     # Controller GUI/API as seen in a web browser
      - "8880/tcp"    # HTTP portal redirection
      - "8843/tcp"    # HTTPS portal redirection
      - "10001/udp"   # AP discovery
      - "27117/tcp"   # DB communications

  mongo:
    image: mongo:4.4
    container_name: MongoDB
    networks:
      unifibridge1:
    restart: unless-stopped
    volumes:
      - /volume1/docker/mongo/db:/data/db
      - /volume1/docker/mongo/dbcfg:/data/configdb

  logs:
    image: bash
    container_name: Unifi-Logs
    networks:
      unifibridge1:
    depends_on:
      - unifi
    command: bash -c 'tail -F /unifi/log/*.log'
    restart: unless-stopped
    volumes:
      - /volume1/docker/unifi2/log:/unifi/log
...
