# Note: 192.168.123.xxx is an example network, you must update all these to match your own.

version: '2'

services:
  pihole:
    container_name: SageCreek-Pi-Hole
    image: pihole/pihole:latest
    hostname: pihole
    domainname: lan             # <-- Update
    mac_address: d0:ca:ab:cd:ef:01
    cap_add:
      - NET_ADMIN
    networks:
      pihole_network:
        ipv4_address: 192.168.110.201   # <-- Update
    volumes:
      - '/volume1/docker/pihole/pihole-configs:/etc/pihole/'
      - '/volume1/docker/pihole/dnsmasq.d-configs:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 8.8.8.8
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    environment:
      ServerIP: 192.168.110.201         # <-- Update (match ipv4_address)
      VIRTUAL_HOST: pihole.lan  # <-- Update (match hostname + domainname)
      WEBPASSWORD: "quga5RHDI@"                   # <-- Add password (if required)
    restart: unless-stopped

networks:
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.110.0/24            # <-- Update
          gateway: 192.168.110.1              # <-- Update
          ip_range: 192.168.110.192/26        # <-- Update
